# Generated by Django 5.2.7 on 2025-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
